import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          inter.className,
          "dark:bg-black dark:text-white min-h-screen flex flex-col"
        )}
      >
        {/* Header */}
        <Header />

        {/* Main content */}
        <main className="flex-1 w-full px-4 md:px-6 lg:px-8 max-w-[1600px] mx-auto">
          {children}
        </main>

        {/* Optional footer placeholder */}
        {/* <footer className="w-full py-4 text-center text-sm text-gray-400">
          © {new Date().getFullYear()} My App
        </footer> */}
      </body>
    </html>
  );
}
